# Generated by Django 6.0.3 on 2026-03-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('went_to_gym', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
