# Generated by Django 6.0.3 on 2026-03-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('did_workout', models.BooleanField()),
                ('why_not', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
